#!/bin/bash

OBJECT="$1"
OPERATION="$2"

if [[ "$OBJECT" == "@VM_NAME@" ]]; then
  case "$OPERATION" in
  "prepare")
    systemctl start libvirt-nosleep@"$OBJECT" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    bash -- "@SCRIPTS_DIR@/vfio-prepare.sh" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    ;;

  "started")
    systemctl start libvirt-nosleep@"$OBJECT" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    bash -- "@SCRIPTS_DIR@/vfio-started.sh" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    ;;

  "stopped")
    systemctl start libvirt-nosleep@"$OBJECT" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    bash -- "@SCRIPTS_DIR@/vfio-stopped.sh" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    ;;

  "release")
    systemctl stop libvirt-nosleep@"$OBJECT" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    bash -- "@SCRIPTS_DIR@/vfio-release.sh" 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
    ;;
  esac
fi
